server:
  port: 8072
  error:
    include-stacktrace: ON_PARAM
    whitelabel:
      enabled: false
logging:
  level:
    com:
      optimagrowth: debug
      netflix: warn
    org:
      springframework:
        web: warn
management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      show-details: always
    env:
      enabled: true
    gateway:
      enabled: true
    configprops:
      enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
spring:
  data:
    redis:
      port: "6379"
      password: ""
      host: redis
  session:
    redis:
      flush-mode: on_save
      namespace: spring:session
    store-type: redis
  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true
        filters:
          - TokenRelay=
      routes:
        - id: organization-service
          uri: lb://organization-service
          predicates:
            - Path=/organization/**
          filters:
            - RewritePath=/organization/(?<path>.*), /$\{path}
            - TokenRelay=
        - id: licensing-service
          uri: lb://licensing-service
          predicates:
            - Path=/license/**
          filters:
            - RewritePath=/license/(?<path>.*), /$\{path}
            - TokenRelay=
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/spmia-realm
        registration:
          keycloak:
            provider: keycloak
            client-secret: VEJh4TpSkAxF85JdYT7SGXsWANAn5Ktf
            client-id: ostock
            scope: openid,profile
            authorization-grant-type: authorization_code
