version: '2.4'
services:
  database:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    ports:
      - "5432:5432"
    mem_limit: 128m
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "ostock_dev"
    # volumes:
    #     - ./init.sql:/docker-entrypoint-initdb.d/1-init.sql
    #     - ./data.sql:/docker-entrypoint-initdb.d/2-data.sql      
    networks:
      backend:
        aliases:
          - "database"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7
    expose:
      - 6379
    mem_limit: 32m    
    networks:
      backend:
        aliases:
          - "redis"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli PING OK"]
      interval: 10s
      timeout: 5s
      retries: 5
  configserver:
    image: ostock/configserver:0.0.4-SNAPSHOT
    ports:
       - "8071:8071"
    mem_limit: 512m
    environment:
      ENCRYPT_KEY: "fje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64Lo"
    networks:
      backend:
        aliases:
          - "configserver"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8071/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
  eurekaserver:
    image: ostock/eurekaserver:0.0.1-SNAPSHOT
    ports:
       - "8070:8070"
    mem_limit: 512m
    environment:
      EUREKA_INSTANCE_HOSTNAME: eurekaserver
      SPRING_CLOUD_CONFIG_URI: "http://configserver:8071"
    depends_on:
      configserver:
        condition: service_healthy
    networks:
      backend:
        aliases:
          - "eurekaserver"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8070/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
  gatewayserver:
    image: ostock/gatewayserver:0.0.3-SNAPSHOT
    ports:
       - "8072:8072"
    mem_limit: 512m
    environment:
      SPRING_CLOUD_CONFIG_URI: "http://configserver:8071"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8070/eureka/"
    depends_on:
      configserver:
        condition: service_healthy
    networks:
      backend:
        aliases:
          - "gatewayserver"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8072/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
  licensingservice:
    image: ostock/licensing-service:0.0.14-SNAPSHOT
    ports:
      - "8083:8083"
    mem_limit: 512m
    environment:
      # JAVA_OPTS: '-Xmx256m -Xms128m'
      SPRING_PROFILES_ACTIVE: "dev"
      SPRING_CLOUD_CONFIG_URI: "http://configserver:8071"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8070/eureka/"
      ENCRYPT_KEY: "fje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64Lo"
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    networks:
      backend:
        aliases:
          - "licensing-service"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8083/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
  organizationservice:
    image: ostock/organization-service:0.0.5-SNAPSHOT
    ports:
      - "8081:8081"
    mem_limit: 512m
    environment:
      # JAVA_OPTS: '-Xmx256m -Xms128m'
      SPRING_PROFILES_ACTIVE: "dev"
      SPRING_CLOUD_CONFIG_URI: "http://configserver:8071"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8070/eureka/"
      ENCRYPT_KEY: "fje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64Lo"
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_started
      eurekaserver:
        condition: service_healthy
    networks:
      backend:
        aliases:
          - "organization-service"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8081/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
  keycloak:
    build:
      context: .
      dockerfile: Dockerfile.keycloak
    command:
      - start-dev
      - --import-realm
    ports:
      - "8080:8080"
    mem_limit: 512m
    environment:
      # JAVA_OPTS: '-Xmx256m -Xms128m'
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      backend:
        aliases:
          - "keycloak"
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f http://localhost:8080/realms/master || exit 1"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
  broker:
    # https://raw.githubusercontent.com/confluentinc/cp-all-in-one/7.5.2-post/cp-all-in-one-kraft/docker-compose.yml
    image: confluentinc/cp-kafka:7.5.3
    hostname: broker
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      # https://www.confluent.io/blog/kafka-listeners-explained/
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker:29092,PLAINTEXT_HOST://node-0:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      # Replace CLUSTER_ID with a unique base64 UUID using "bin/kafka-storage.sh random-uuid"
      # See https://docs.confluent.io/kafka/operations-tools/kafka-tools.html#kafka-storage-sh
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
networks:
  backend:
    driver: bridge
